/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 08-Aug-2016 10:53:12 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_site_pages_site_pages]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [site_pages] DROP CONSTRAINT [FK_site_pages_site_pages]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_connections_cities1]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [connections] DROP CONSTRAINT [FK_connections_cities1]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_connections_cities2]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [connections] DROP CONSTRAINT [FK_connections_cities2]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[FK_computers_rooms]') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1) 
ALTER TABLE [computers] DROP CONSTRAINT [FK_computers_rooms]
GO

/* Drop Tables */

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[test_counts]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [test_counts]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[table_with_nulls]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [table_with_nulls]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[site_pages]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [site_pages]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[rooms]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [rooms]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[overflow]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [overflow]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[dates]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [dates]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[connections]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [connections]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[computers]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [computers]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('[cities]') AND OBJECTPROPERTY(id, 'IsUserTable') = 1) 
DROP TABLE [cities]
GO

/* Create Tables */

CREATE TABLE [test_counts]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[fni] int NULL,
	[fwi] int NULL,
	[fni_nn] int NOT NULL,
	[fwi_nn] int NOT NULL
)
GO

CREATE TABLE [table_with_nulls]
(
	[x] int NULL
)
GO

CREATE TABLE [site_pages]
(
	[sp_id] int NOT NULL IDENTITY (1, 1),
	[sp_parent] int NULL,
	[sp_name] nvarchar(200) NULL
)
GO

CREATE TABLE [rooms]
(
	[r_id] int NOT NULL IDENTITY (1, 1),
	[r_name] nvarchar(50) NOT NULL,
	[r_space] tinyint NOT NULL
)
GO

CREATE TABLE [overflow]
(
	[x] int NULL
)
GO

CREATE TABLE [dates]
(
	[d] date NULL
)
GO

CREATE TABLE [connections]
(
	[cn_from] int NOT NULL,
	[cn_to] int NOT NULL,
	[cn_cost] money NULL,
	[cn_bidir] char(1) NOT NULL
)
GO

CREATE TABLE [computers]
(
	[c_id] int NOT NULL IDENTITY (1, 1),
	[c_room] int NULL,
	[c_name] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [cities]
(
	[ct_id] int NOT NULL IDENTITY (1, 1),
	[ct_name] nvarchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [test_counts] 
 ADD CONSTRAINT [PK_test_counts]
	PRIMARY KEY CLUSTERED ([id])
GO

CREATE INDEX [idx_fwi] 
 ON [test_counts] ([fwi] ASC)
GO

CREATE INDEX [idx_fwi_nn] 
 ON [test_counts] ([fwi_nn] ASC)
GO

ALTER TABLE [site_pages] 
 ADD CONSTRAINT [PK_site_pages]
	PRIMARY KEY CLUSTERED ([sp_id])
GO

ALTER TABLE [rooms] 
 ADD CONSTRAINT [PK_rooms]
	PRIMARY KEY CLUSTERED ([r_id])
GO

CREATE INDEX [idx_d] 
 ON [dates] ([d] ASC)
GO

ALTER TABLE [connections] 
 ADD CONSTRAINT [PK_connections]
	PRIMARY KEY CLUSTERED ([cn_from],[cn_to])
GO

ALTER TABLE [connections] 
 ADD CONSTRAINT [CHK_bidir] CHECK ([cn_bidir] IN ('N','Y'))
GO

ALTER TABLE [computers] 
 ADD CONSTRAINT [PK_computers]
	PRIMARY KEY CLUSTERED ([c_id])
GO

ALTER TABLE [cities] 
 ADD CONSTRAINT [PK_cities]
	PRIMARY KEY CLUSTERED ([ct_id])
GO

/* Create Foreign Key Constraints */

ALTER TABLE [site_pages] ADD CONSTRAINT [FK_site_pages_site_pages]
	FOREIGN KEY ([sp_parent]) REFERENCES [site_pages] ([sp_id])
GO

ALTER TABLE [connections] ADD CONSTRAINT [FK_connections_cities1]
	FOREIGN KEY ([cn_from]) REFERENCES [cities] ([ct_id]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [connections] ADD CONSTRAINT [FK_connections_cities2]
	FOREIGN KEY ([cn_to]) REFERENCES [cities] ([ct_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [computers] ADD CONSTRAINT [FK_computers_rooms]
	FOREIGN KEY ([c_room]) REFERENCES [rooms] ([r_id]) ON DELETE Cascade ON UPDATE Cascade
GO
