--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.864
--   Created On : Monday, 08 August, 2016 
--   DBMS       : Oracle 
--   -------------------------------------------------- 



--  Drop Tables, Stored Procedures and Views 

DROP TRIGGER "TRG_authors_a_id"
;


DROP SEQUENCE "SEQ_authors_a_id"
;


DROP TABLE "authors" CASCADE CONSTRAINTS
;
DROP TRIGGER "TRG_books_b_id"
;


DROP SEQUENCE "SEQ_books_b_id"
;


DROP TABLE "books" CASCADE CONSTRAINTS
;
DROP TRIGGER "TRG_genres_g_id"
;


DROP SEQUENCE "SEQ_genres_g_id"
;


DROP TABLE "genres" CASCADE CONSTRAINTS
;
DROP TABLE "m2m_books_authors" CASCADE CONSTRAINTS
;
DROP TABLE "m2m_books_genres" CASCADE CONSTRAINTS
;
DROP TRIGGER "TRG_subscribers_s_id"
;


DROP SEQUENCE "SEQ_subscribers_s_id"
;


DROP TABLE "subscribers" CASCADE CONSTRAINTS
;
DROP TRIGGER "TRG_subscriptions_sb_id"
;


DROP SEQUENCE "SEQ_subscriptions_sb_id"
;


DROP TABLE "subscriptions" CASCADE CONSTRAINTS
;

--  Create Tables 
CREATE TABLE "authors"
(
	"a_id"  NUMBER(10) NOT NULL,
	"a_name" NVARCHAR2(150) NOT NULL
)
;


CREATE TABLE "books"
(
	"b_id"      NUMBER(10) NOT NULL,
	"b_name"    NVARCHAR2(150) NOT NULL,
	"b_year"    NUMBER(5) NOT NULL,
	"b_quantity" NUMBER(5) NOT NULL
)
;


CREATE TABLE "genres"
(
	"g_id"  NUMBER(10) NOT NULL,
	"g_name" NVARCHAR2(150) NOT NULL
)
;


CREATE TABLE "m2m_books_authors"
(
	"b_id" NUMBER(10) NOT NULL,
	"a_id" NUMBER(10) NOT NULL
)
;


CREATE TABLE "m2m_books_genres"
(
	"b_id" NUMBER(10) NOT NULL,
	"g_id" NUMBER(10) NOT NULL
)
;


CREATE TABLE "subscribers"
(
	"s_id"  NUMBER(10) NOT NULL,
	"s_name" NVARCHAR2(150) NOT NULL
)
;


CREATE TABLE "subscriptions"
(
	"sb_id"        NUMBER(10) NOT NULL,
	"sb_subscriber" NUMBER(10) NOT NULL,
	"sb_book"      NUMBER(10) NOT NULL,
	"sb_start"     DATE NOT NULL,
	"sb_finish"    DATE NOT NULL,
	"sb_is_active" CHAR(1) NOT NULL
)
;



--  Create Primary Key Constraints 
ALTER TABLE "authors" ADD CONSTRAINT "PK_authors" 
	PRIMARY KEY ("a_id") 
 USING INDEX 
;

ALTER TABLE "books" ADD CONSTRAINT "PK_books" 
	PRIMARY KEY ("b_id") 
 USING INDEX 
;

ALTER TABLE "genres" ADD CONSTRAINT "PK_genres" 
	PRIMARY KEY ("g_id") 
 USING INDEX 
;

ALTER TABLE "m2m_books_authors" ADD CONSTRAINT "PK_m2m_books_authors" 
	PRIMARY KEY ("b_id", "a_id") 
 USING INDEX 
;

ALTER TABLE "m2m_books_genres" ADD CONSTRAINT "PK_m2m_books_genres" 
	PRIMARY KEY ("b_id", "g_id") 
 USING INDEX 
;

ALTER TABLE "subscribers" ADD CONSTRAINT "PK_subscribers" 
	PRIMARY KEY ("s_id") 
 USING INDEX 
;

ALTER TABLE "subscriptions" ADD CONSTRAINT "PK_subscriptions" 
	PRIMARY KEY ("sb_id") 
 USING INDEX 
;


--  Create Indexes 
ALTER TABLE "genres"
	ADD CONSTRAINT "UQ_genres_g_name" UNIQUE ("g_name")
 USING INDEX 
;

ALTER TABLE "subscriptions"
ADD CONSTRAINT "check_enum" CHECK ("sb_is_active" IN ('Y', 'N'))
;


--  Create Foreign Key Constraints 
ALTER TABLE "m2m_books_authors" ADD CONSTRAINT "FK_m2m_books_authors_authors" 
	FOREIGN KEY ("a_id") REFERENCES "authors" ("a_id")
ON DELETE CASCADE
;

ALTER TABLE "m2m_books_authors" ADD CONSTRAINT "FK_m2m_books_authors_books" 
	FOREIGN KEY ("b_id") REFERENCES "books" ("b_id")
ON DELETE CASCADE
;

ALTER TABLE "m2m_books_genres" ADD CONSTRAINT "FK_m2m_books_genres_books" 
	FOREIGN KEY ("b_id") REFERENCES "books" ("b_id")
ON DELETE CASCADE
;

ALTER TABLE "m2m_books_genres" ADD CONSTRAINT "FK_m2m_books_genres_genres" 
	FOREIGN KEY ("g_id") REFERENCES "genres" ("g_id")
ON DELETE CASCADE
;

ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_subscriptions_books" 
	FOREIGN KEY ("sb_book") REFERENCES "books" ("b_id")
ON DELETE CASCADE
;

ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_subscriptions_subscribers" 
	FOREIGN KEY ("sb_subscriber") REFERENCES "subscribers" ("s_id")
ON DELETE CASCADE
;






--  Create Triggers 
CREATE SEQUENCE "SEQ_authors_a_id" 
    INCREMENT BY 1 
    START WITH 1 
    NOMAXVALUE 
    MINVALUE 1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;



CREATE OR REPLACE TRIGGER "TRG_authors_a_id" 
	BEFORE INSERT 
	ON "authors" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_authors_a_id".NEXTVAL 
		INTO :NEW."a_id" 
		FROM DUAL; 
	END;
/
CREATE SEQUENCE "SEQ_books_b_id" 
    INCREMENT BY 1 
    START WITH 1 
    NOMAXVALUE 
    MINVALUE 1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;



CREATE OR REPLACE TRIGGER "TRG_books_b_id" 
	BEFORE INSERT 
	ON "books" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_books_b_id".NEXTVAL 
		INTO :NEW."b_id" 
		FROM DUAL; 
	END;
/
CREATE SEQUENCE "SEQ_genres_g_id" 
    INCREMENT BY 1 
    START WITH 1 
    NOMAXVALUE 
    MINVALUE 1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;



CREATE OR REPLACE TRIGGER "TRG_genres_g_id" 
	BEFORE INSERT 
	ON "genres" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_genres_g_id".NEXTVAL 
		INTO :NEW."g_id" 
		FROM DUAL; 
	END;
/
CREATE SEQUENCE "SEQ_subscribers_s_id" 
    INCREMENT BY 1 
    START WITH 1 
    NOMAXVALUE 
    MINVALUE 1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;



CREATE OR REPLACE TRIGGER "TRG_subscribers_s_id" 
	BEFORE INSERT 
	ON "subscribers" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_subscribers_s_id".NEXTVAL 
		INTO :NEW."s_id" 
		FROM DUAL; 
	END;
/
CREATE SEQUENCE "SEQ_subscriptions_sb_id" 
    INCREMENT BY 1 
    START WITH 1 
    NOMAXVALUE 
    MINVALUE 1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;



CREATE OR REPLACE TRIGGER "TRG_subscriptions_sb_id" 
	BEFORE INSERT 
	ON "subscriptions" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_subscriptions_sb_id".NEXTVAL 
		INTO :NEW."sb_id" 
		FROM DUAL; 
	END;
/
