/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 08-Aug-2016 21:21:02 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `test_counts` CASCADE
;

DROP TABLE IF EXISTS `table_with_nulls` CASCADE
;

DROP TABLE IF EXISTS `site_pages` CASCADE
;

DROP TABLE IF EXISTS `rooms` CASCADE
;

DROP TABLE IF EXISTS `overflow` CASCADE
;

DROP TABLE IF EXISTS `dates` CASCADE
;

DROP TABLE IF EXISTS `connections` CASCADE
;

DROP TABLE IF EXISTS `computers` CASCADE
;

DROP TABLE IF EXISTS `cities` CASCADE
;

/* Create Tables */

CREATE TABLE `test_counts`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`fni` INT 	 NULL,
	`fwi` INT 	 NULL,
	`fni_nn` INT NOT NULL,
	`fwi_nn` INT NOT NULL,
	CONSTRAINT `PK_test_counts` PRIMARY KEY (`id`)
)

;

CREATE TABLE `table_with_nulls`
(
	`x` INT 	 NULL
)

;

CREATE TABLE `site_pages`
(
	`sp_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`sp_parent` INT 	 UNSIGNED NULL,
	`sp_name` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_site_pages` PRIMARY KEY (`sp_id`)
)

;

CREATE TABLE `rooms`
(
	`r_id` INT NOT NULL AUTO_INCREMENT,
	`r_name` VARCHAR(50) NOT NULL,
	`r_space` TINYINT NOT NULL,
	CONSTRAINT `PK_rooms` PRIMARY KEY (`r_id`)
)

;

CREATE TABLE `overflow`
(
	`x` INT 	 NULL
)

;

CREATE TABLE `dates`
(
	`d` DATE 	 NULL
)

;

CREATE TABLE `connections`
(
	`cn_from` INT NOT NULL,
	`cn_to` INT NOT NULL,
	`cn_cost` DOUBLE 	 NULL,
	`cn_bidir` ENUM ('N','Y') NOT NULL,
	CONSTRAINT `PK_connections` PRIMARY KEY (`cn_from`,`cn_to`)
)

;

CREATE TABLE `computers`
(
	`c_id` INT NOT NULL AUTO_INCREMENT,
	`c_room` INT 	 NULL,
	`c_name` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_computers` PRIMARY KEY (`c_id`)
)

;

CREATE TABLE `cities`
(
	`ct_id` INT NOT NULL AUTO_INCREMENT,
	`ct_name` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_cities` PRIMARY KEY (`ct_id`)
)

;

/* Create Indexes, Uniques, Checks */

ALTER TABLE `test_counts` 
 ADD INDEX `idx_fwi` (`fwi` ASC)
;

ALTER TABLE `test_counts` 
 ADD INDEX `idx_fwi_nn` (`fwi_nn` ASC)
;

ALTER TABLE `dates` 
 ADD INDEX `idx_d` (`d` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `site_pages` 
 ADD CONSTRAINT `FK_site_pages_site_pages`
	FOREIGN KEY (`sp_parent`) REFERENCES `site_pages` (`sp_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `connections` 
 ADD CONSTRAINT `FK_connections_cities1`
	FOREIGN KEY (`cn_from`) REFERENCES `cities` (`ct_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `connections` 
 ADD CONSTRAINT `FK_connections_cities2`
	FOREIGN KEY (`cn_to`) REFERENCES `cities` (`ct_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `computers` 
 ADD CONSTRAINT `FK_computers_rooms`
	FOREIGN KEY (`c_room`) REFERENCES `rooms` (`r_id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 ;
